# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repolink', models.CharField(max_length=100)),
                ('usage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.CharField(max_length=5000)),
                ('breif_description', models.CharField(max_length=500)),
                ('version', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('pubdate', models.DateTimeField(verbose_name='date published')),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
    ]
