# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 18:49
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('home', '0002_remove_paper_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
