# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_paper_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='ids',
            new_name='uuid',
        ),
    ]
