# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20151204_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paper',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
