# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20151205_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='codelink',
            name='title',
            field=models.CharField(default='Link to implementation', max_length=100, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='codelink',
            name='uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.CodeLink'),
        ),
    ]
