# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20151205_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codelink',
            name='uuid',
        ),
    ]
