# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_codelink_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(max_length=5000)),
            ],
        ),
    ]
