# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_paper_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='links',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.AdditionalLinks'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='repo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.CodeLink'),
        ),
    ]
